### ISSUE TITLE
Better quality logo/icon

### ISSUE THREAD

**Issue by jdorfman** [mprove-io/mprove#1]
👋 Mprove team!

We (StackShare) would like to feature your tool in our weekly newsletter tomorrow. The logo we have now is ok-ish but we would like to present the tool with a higher quality logo/icon (400 x 400px minimum).

If you can attach it here by 3 PM PST that would be awesome. Thanks =)

**Comment by akalitenya** [comment]
![800x800](https://user-images.githubusercontent.com/11003561/55426434-35f5b680-559e-11e9-9e99-e29a3f522c23.png)
![600x600](https://user-images.githubusercontent.com/11003561/55426435-35f5b680-559e-11e9-80a8-fd0b673da871.png)
![400x400](https://user-images.githubusercontent.com/11003561/55426436-368e4d00-559e-11e9-8dd4-de47dfaaffb5.png)

**Comment by akalitenya** [comment]
![2096x525](https://user-images.githubusercontent.com/11003561/55427342-355e1f80-55a0-11e9-9e7f-fb93e00b670a.png)
