### ISSUE TITLE
How i can run from Windows 10 ?

### ISSUE THREAD

**Issue by psilvao** [mprove-io/mprove#97]
Hi team

   a big thanks for your work, but i can't find any documentation for to run your software in windows, can you give me please the steps for to do it?

Regards
Pablo

**Comment by akalitenya** [comment]
Hi Pablo

I will make deployment instructions this week (by Friday)

**Comment by psilvao** [comment]
ok thanks, i want to run inside the company for our customers

**Comment by akalitenya** [comment]
I've added docker-compose instructions for local deployment to the project's readme file. Feel free to reopen this issue if you have any questions.
